language: python
python:
  - "3.7"
before_install:
  - curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install
  - python firedrake-install
install:
  - pwd
  - ls



